Hw hibernate user service
mate-academy/hibernate-user-service-hw pull request #199
Opened 2022-04-12 14:36 UTC by OlehMytiai

2022-04-12 15:00 UTC, NazariiYatsiuk approved these changes
I see no problems

2022-04-13 07:31 UTC, KostyaNikiforov requested changes

2022-04-13 07:31 UTC, KostyaNikiforov commented on src/main/java/mate/academy/security/AuthenticationServiceImpl.java
> +        }
Just for the future, it is a good practice to move big conditions to a separate method

2022-04-13 07:31 UTC, KostyaNikiforov commented on src/main/java/mate/academy/util/HashUtil.java
> +
Empty line

2022-04-13 07:31 UTC, KostyaNikiforov commented on src/main/java/mate/academy/util/HashUtil.java
> +        byte[] salt = new byte[16];
Let's make this value constant too

2022-04-13 08:40 UTC, KostyaNikiforov approved these changes

2022-11-12 22:57 UTC, closed without merging