implemented user service
mate-academy/hibernate-user-service-hw pull request #62
Opened 2021-08-06 14:00 UTC by Daniel1004K

…ibernate.cfg.xml, created HashUtilSha512.java

2021-08-06 14:06 UTC, nikdagaev requested changes

2021-08-06 14:06 UTC, nikdagaev commented on src/main/java/mate/academy/model/User.java
> +    private String login;
Let’s make the login unique. - from Common Mistakes

2021-08-06 14:06 UTC, nikdagaev commented on src/main/java/mate/academy/service/impl/AuthenticationServiceImpl.java
> +        throw new AuthenticationException("Login or password is wrong ");
Create only one condition for throwing AuthenticationException in login() method. You may combine two checks: whether the user has been found by login and does passwords match. - from Common mistakes)

2021-08-08 08:56 UTC, nikdagaev approved these changes

2021-08-09 09:54 UTC, Sofasmile requested changes

2021-08-09 09:54 UTC, Sofasmile commented on src/main/java/mate/academy/service/impl/AuthenticationServiceImpl.java
> +            throw new AuthenticationException("User with email " + email + " exist");
better throw other custom exception, because authentication isn't the same as registration

2021-08-09 09:54 UTC, Sofasmile commented on src/main/java/mate/academy/service/impl/AuthenticationServiceImpl.java
> +        if (userService.findByEmail(email).isPresent() || password.equals("")) {
```suggestion
        if (userService.findByEmail(email).isPresent() || password.isEmpty())) {
```

2021-08-09 09:54 UTC, Sofasmile commented on src/main/java/mate/academy/util/HashUtilSha512.java
> +            for (byte b : digest) {
```suggestion
            for (byte item/element/symbol : digest) {
```

2021-08-09 11:02 UTC, Sofasmile requested changes

2021-08-09 11:02 UTC, Sofasmile commented on src/main/java/mate/academy/service/impl/AuthenticationServiceImpl.java
> +            throw new AuthenticationException("User with email " + email + " exist");
```suggestion
            throw new RegistrationException("User with email " + email + " exist");
```

2021-08-09 11:02 UTC, Sofasmile commented on src/main/java/mate/academy/service/impl/UserServiceImpl.java
> +        return userDao.add(user);
is your password hashed?

2021-08-09 11:45 UTC, Sofasmile requested changes

2021-08-09 11:45 UTC, Sofasmile commented on src/main/java/mate/academy/service/AuthenticationService.java
> +            throws AuthenticationException, RegistrationException;
```suggestion
            throws RegistrationException;
```

2021-08-09 11:45 UTC, Sofasmile commented on src/main/java/mate/academy/service/impl/AuthenticationServiceImpl.java
>          return userService.add(new User(email, password, HashUtilSha512.getSalt()));
ми тут уже передаємо сіль. Тому в методі `User add(User user)` ми можемо використовувати уже згенеровану сіль, щоб не робити це двічі. Або ж давай тут не будемо генерувати сіль, а будемо робити це на рівні UserServiceImpl

2021-08-09 13:11 UTC, Sofasmile approved these changes

2023-04-07 12:45 UTC, closed without merging